# Generated by Django 5.0.7 on 2024-07-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qusetion',
            new_name='Question',
        ),
    ]
