# Generated by Django 5.0.7 on 2024-07-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_name',
        ),
    ]
